version: "3.9"
services:
  backend:
    build: ./apps/backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/usr/src/app
      - ./data:/usr/src/app/data
    depends_on:
      - frontend
  frontend:
    build: ./apps/frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/usr/src/app
    environment:
      - VITE_API_BASE=http://localhost:4000


